# Generated by Django 4.2.25 on 2025-11-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FOOD_NAME', models.CharField(blank=True, max_length=100, null=True)),
                ('FOOD_CATAGORY', models.CharField(blank=True, max_length=100, null=True)),
                ('FOOD_PRICE', models.IntegerField(blank=True, null=True)),
                ('FOOD_DESCRIPTION', models.CharField(blank=True, max_length=100, null=True)),
                ('FOOD_IMAGE', models.ImageField(blank=True, null=True, upload_to='food_catagory')),
            ],
        ),
    ]
