# Generated by Django 4.2.25 on 2025-11-13 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CONTACT_NAME', models.CharField(blank=True, max_length=100, null=True)),
                ('CONTACT_EMAIL', models.EmailField(blank=True, max_length=254, null=True)),
                ('CONTACT_SUBJECTS', models.CharField(blank=True, max_length=100, null=True)),
                ('CONTACT_MESSAGE', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
